language: node_js
node_js:
  - "10"
notifications:
  email: false
before_script:
script:
  - npm install
  - npm run build
  - test -f build/ag-icons.woff
  - test -f build/ag-icons.css
branches:
  only: 
    - master
