name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build icon font artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v3
    - uses: actions/checkout@v2.5.0
    - uses: actions/cache@v3
    # https://github.com/actions/cache/blob/main/examples.md#node---npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-    
    - name: NPM install
      run: npm install
    - name: Run build
      run: |
        npm run build
        test -f build/font/ag-icons.woff
        test -f build/css/ag-icons.css
        test -f build/index.html
    - name: Upload font and css
      uses: actions/upload-artifact@v3
      with:
        name: abapGit-font-and-css
        path: ./build/
        if-no-files-found: error
        retention-days: 7
  deploy:
    name: Deploy rendered icons
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'abapGit/icon-font' }}
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: abapGit-font-and-css
    - name: Display structure of downloaded files and move file to public dir
      run: |
        ls -R
        zip -j assets.zip font/ag-icons.woff css/ag-icons.css
        mkdir public
        shopt -s extglob
        mv !(public) public
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./public        
        cname: icons.abapgit.org
        publish_branch: main
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        force_orphan: true        
        external_repository: abapGit/icons.abapgit.org
