name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        npm install
        npm run build
        test -f build/ag-icons.woff
        test -f build/ag-icons.css
    - name: Upload font and css
      uses: actions/upload-artifact@main
      with:
        name: abapGit-font-and-css
        path: ./build/**/*.*
        retention-days: 7
  deploy:
    name: Deploy rendered icons
    runs-on: ubuntu-latest
    needs: build
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'abapGit/icon-font' }}
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: abapGit-font-and-css
    - name: Display structure of downloaded files
      run: ls -R
