name: test-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-build:
    name: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - name: Run test build
        run: |
          npm install
          npm run build
          test -f build/ag-icons.woff
          test -f build/ag-icons.css
